# Form implementation generated from reading ui file 'main_app_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BantuanAppBase(object):
    def setupUi(self, BantuanAppBase):
        BantuanAppBase.setObjectName("BantuanAppBase")
        BantuanAppBase.resize(390, 488)
        BantuanAppBase.setBaseSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(BantuanAppBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonTambah = QtWidgets.QPushButton(parent=BantuanAppBase)
        self.pushButtonTambah.setObjectName("pushButtonTambah")
        self.verticalLayout.addWidget(self.pushButtonTambah)
        self.pushButtonLihat = QtWidgets.QPushButton(parent=BantuanAppBase)
        self.pushButtonLihat.setObjectName("pushButtonLihat")
        self.verticalLayout.addWidget(self.pushButtonLihat)
        self.pushButtonCari = QtWidgets.QPushButton(parent=BantuanAppBase)
        self.pushButtonCari.setObjectName("pushButtonCari")
        self.verticalLayout.addWidget(self.pushButtonCari)
        self.pushButtonHapus = QtWidgets.QPushButton(parent=BantuanAppBase)
        self.pushButtonHapus.setObjectName("pushButtonHapus")
        self.verticalLayout.addWidget(self.pushButtonHapus)
        self.pushButtonKeluar = QtWidgets.QPushButton(parent=BantuanAppBase)
        self.pushButtonKeluar.setObjectName("pushButtonKeluar")
        self.verticalLayout.addWidget(self.pushButtonKeluar)
        self.textEditOutput = QtWidgets.QTextEdit(parent=BantuanAppBase)
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.verticalLayout.addWidget(self.textEditOutput)

        self.retranslateUi(BantuanAppBase)
        QtCore.QMetaObject.connectSlotsByName(BantuanAppBase)

    def retranslateUi(self, BantuanAppBase):
        _translate = QtCore.QCoreApplication.translate
        BantuanAppBase.setWindowTitle(_translate("BantuanAppBase", "Bantuan Warga Sukamaju"))
        self.pushButtonTambah.setText(_translate("BantuanAppBase", "➕ Tambah Data Warga"))
        self.pushButtonLihat.setText(_translate("BantuanAppBase", "📋 Lihat Semua Data"))
        self.pushButtonCari.setText(_translate("BantuanAppBase", "🔍 Cari Data"))
        self.pushButtonHapus.setText(_translate("BantuanAppBase", "❌ Hapus Data"))
        self.pushButtonKeluar.setText(_translate("BantuanAppBase", "🚪 Keluar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BantuanAppBase = QtWidgets.QWidget()
    ui = Ui_BantuanAppBase()
    ui.setupUi(BantuanAppBase)
    BantuanAppBase.show()
    sys.exit(app.exec())
