# Form implementation generated from reading ui file 'tambah_data_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TambahDataDialogBase(object):
    def setupUi(self, TambahDataDialogBase):
        TambahDataDialogBase.setObjectName("TambahDataDialogBase")
        TambahDataDialogBase.resize(364, 152)
        TambahDataDialogBase.setBaseSize(QtCore.QSize(300, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(TambahDataDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=TambahDataDialogBase)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditNama = QtWidgets.QLineEdit(parent=TambahDataDialogBase)
        self.lineEditNama.setObjectName("lineEditNama")
        self.verticalLayout.addWidget(self.lineEditNama)
        self.lineEditNIK = QtWidgets.QLineEdit(parent=TambahDataDialogBase)
        self.lineEditNIK.setObjectName("lineEditNIK")
        self.verticalLayout.addWidget(self.lineEditNIK)
        self.lineEditBantuan = QtWidgets.QLineEdit(parent=TambahDataDialogBase)
        self.lineEditBantuan.setObjectName("lineEditBantuan")
        self.verticalLayout.addWidget(self.lineEditBantuan)
        self.pushButtonSimpan = QtWidgets.QPushButton(parent=TambahDataDialogBase)
        self.pushButtonSimpan.setObjectName("pushButtonSimpan")
        self.verticalLayout.addWidget(self.pushButtonSimpan)

        self.retranslateUi(TambahDataDialogBase)
        QtCore.QMetaObject.connectSlotsByName(TambahDataDialogBase)

    def retranslateUi(self, TambahDataDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TambahDataDialogBase.setWindowTitle(_translate("TambahDataDialogBase", "Tambah Data Warga"))
        self.label.setText(_translate("TambahDataDialogBase", "Masukkan Data Warga"))
        self.lineEditNama.setText(_translate("TambahDataDialogBase", "Nama:"))
        self.lineEditNama.setPlaceholderText(_translate("TambahDataDialogBase", "Nama Warga"))
        self.lineEditNIK.setText(_translate("TambahDataDialogBase", "NIK:"))
        self.lineEditNIK.setPlaceholderText(_translate("TambahDataDialogBase", "NIK"))
        self.lineEditBantuan.setText(_translate("TambahDataDialogBase", "Bantuan:"))
        self.lineEditBantuan.setPlaceholderText(_translate("TambahDataDialogBase", "Jenis Bantuan"))
        self.pushButtonSimpan.setText(_translate("TambahDataDialogBase", "Simpan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TambahDataDialogBase = QtWidgets.QDialog()
    ui = Ui_TambahDataDialogBase()
    ui.setupUi(TambahDataDialogBase)
    TambahDataDialogBase.show()
    sys.exit(app.exec())
